[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "/login"
  status = 301
  force = true

[[redirects]]
  from = "/signup"
  to = "/signup"
  status = 301
  force = true
